# Generated by Django 3.1.7 on 2021-03-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_product_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
    ]
