# Generated by Django 3.1.7 on 2021-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_remove_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='originalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
