# Generated by Django 3.1.7 on 2021-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20210324_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ArrivalDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ExpireDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ExtendTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='XXS', max_length=3),
        ),
    ]
