# Generated by Django 3.1.7 on 2021-03-23 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20210324_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ArrivalDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
