# Generated by Django 3.1.7 on 2021-03-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20210324_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('UNIQLOID', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('wishing_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['username', 'UNIQLOID'],
            },
        ),
    ]
