# Generated by Django 3.1.7 on 2021-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_sellerapplicationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplicationrecord',
            name='item_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
