# Generated by Django 3.1.7 on 2021-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_application_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=10)),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
    ]
