# Generated by Django 3.1.7 on 2021-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='sizeName',
            new_name='size',
        ),
    ]
