# Generated by Django 3.1.7 on 2021-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20210401_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_name_ch',
            field=models.CharField(default='', max_length=10),
        ),
    ]
