# Generated by Django 3.1.7 on 2021-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_color_color_name_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_square_url',
            field=models.URLField(default=''),
        ),
    ]
