# Generated by Django 3.1.7 on 2021-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_remove_color_color_square_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_chip_url',
            field=models.URLField(default=''),
        ),
    ]
