# Generated by Django 3.1.7 on 2021-04-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_color_color_chip_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_code']},
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_chip_url',
        ),
    ]
