# Generated by Django 3.1.7 on 2021-04-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_option_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='Size',
            new_name='size',
        ),
    ]
