# Generated by Django 3.1.7 on 2021-04-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_remove_option_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='size',
        ),
    ]
