# Generated by Django 3.1.7 on 2021-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_remove_option_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='XXS', max_length=3),
        ),
    ]
