# Generated by Django 3.1.7 on 2021-04-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_option_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='size',
        ),
    ]
