# Generated by Django 3.1.7 on 2021-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_onehalfoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalogue.OnehalfOption', verbose_name='Options'),
        ),
    ]
