# Generated by Django 3.1.7 on 2021-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalogue.OnehalfOption', verbose_name='OnehalfOptions'),
        ),
    ]
