# Generated by Django 3.1.7 on 2021-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_auto_20210402_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AlterField(
            model_name='options',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('choices', 'Choices')], default='text', max_length=255, verbose_name='Type'),
        ),
    ]
