# Generated by Django 3.1.7 on 2021-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20210402_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnehalfOption',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('choices', 'Choices')], default='text', max_length=255, verbose_name='Type'),
        ),
    ]
