# Generated by Django 3.1.7 on 2021-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20210412_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_records',
            name='color_eng',
            field=models.CharField(default='', max_length=20),
        ),
    ]
