# Generated by Django 3.1.7 on 2021-04-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_application_records_color_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_records',
            old_name='color_ch',
            new_name='color_name_ch',
        ),
        migrations.RenameField(
            model_name='application_records',
            old_name='color_eng',
            new_name='color_name_eng',
        ),
    ]
