# Generated by Django 3.1.7 on 2021-04-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20210412_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
    ]
