# Generated by Django 3.1.7 on 2021-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_remove_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'upc']},
        ),
        migrations.AddField(
            model_name='application_records',
            name='application_submit_date',
            field=models.DateField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
