# Generated by Django 3.1.7 on 2021-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_auto_20210421_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='application_submit_date',
            field=models.DateField(auto_now_add=True, verbose_name='更新時間'),
        ),
    ]
