# Generated by Django 3.1.7 on 2021-04-20 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_auto_20210421_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_records',
            name='application_submit_date',
        ),
        migrations.AddField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='儲存日期'),
        ),
        migrations.AddField(
            model_name='application_records',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最後修改日期'),
        ),
    ]
