# Generated by Django 3.1.7 on 2021-04-20 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0066_auto_20210421_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 1, 41, 9, 932993), verbose_name='儲存日期'),
        ),
    ]
