# Generated by Django 3.1.7 on 2021-04-21 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0068_auto_20210421_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 1, 54, 29, 989077), verbose_name='儲存日期'),
        ),
        migrations.AlterField(
            model_name='application_records',
            name='selling_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 1, 54, 29, 989077), verbose_name='最後修改日期'),
        ),
    ]
