# Generated by Django 3.1.7 on 2021-04-27 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0079_auto_20210427_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 23, 10, 47, 288266), verbose_name='儲存日期'),
        ),
        migrations.AlterField(
            model_name='application_records',
            name='instock_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 23, 10, 47, 289268), null=True, verbose_name='上架日期'),
        ),
    ]
