# Generated by Django 2.2 on 2021-05-14 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0080_auto_20210427_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 9, 7, 593330), verbose_name='儲存日期'),
        ),
        migrations.AlterField(
            model_name='application_records',
            name='instock_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 14, 17, 9, 7, 593330), null=True, verbose_name='上架日期'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('integer', '整數'), ('boolean', ' '), ('float', '浮點數'), ('date', '日期'), ('choices', 'Choices')], default='text', max_length=255, verbose_name='類型'),
        ),
    ]
