# Generated by Django 2.2 on 2021-05-18 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0087_auto_20210516_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_records',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 13, 9, 49, 152375), verbose_name='儲存日期'),
        ),
        migrations.AlterField(
            model_name='application_records',
            name='instock_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 13, 9, 49, 152375), null=True, verbose_name='上架日期'),
        ),
    ]
