# Generated by Django 3.1.7 on 2021-04-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_sellerrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrevenue',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
