# Generated by Django 3.1.7 on 2021-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_sellerrevenue_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrevenue',
            name='withdrawn',
            field=models.IntegerField(default=0),
        ),
    ]
