# Generated by Django 3.1.7 on 2021-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_sellerrevenue_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrevenue',
            name='totalRevenue',
            field=models.IntegerField(default=0),
        ),
    ]
