# Generated by Django 3.1.7 on 2021-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_sellerrevenue_totalrevenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerrevenue',
            options={'ordering': ['seller', 'totalRevenue']},
        ),
        migrations.AlterField(
            model_name='sellerrevenue',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance 餘額'),
        ),
        migrations.AlterField(
            model_name='sellerrevenue',
            name='totalRevenue',
            field=models.IntegerField(default=0, verbose_name='totalRevenue 個人銷售總額'),
        ),
        migrations.AlterField(
            model_name='sellerrevenue',
            name='withdrawn',
            field=models.IntegerField(default=0, verbose_name='withdrawn 已提領'),
        ),
    ]
