# Generated by Django 3.1.7 on 2021-04-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210423_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbankaccount',
            name='bank_account',
            field=models.CharField(default='', max_length=20, verbose_name='bank_account 銀行帳號'),
        ),
        migrations.AlterField(
            model_name='sellerbankaccount',
            name='bank_code',
            field=models.CharField(default='', max_length=3, verbose_name='bank_code 銀行代碼'),
        ),
        migrations.AlterField(
            model_name='sellerbankaccount',
            name='bank_name',
            field=models.CharField(default='', max_length=20, verbose_name='bank_name 銀行名稱'),
        ),
    ]
