# Generated by Django 3.1.7 on 2021-04-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
        ('seller', '0003_auto_20210423_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbankaccount',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
