# Generated by Django 3.1.7 on 2021-04-25 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
        ('seller', '0004_auto_20210423_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWithdrawRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=datetime.datetime(2021, 4, 25, 0, 52, 46, 210924), verbose_name='儲存日期')),
                ('transfered_date', models.DateTimeField(blank=True, null=True, verbose_name='匯款完成日期')),
                ('status', models.CharField(choices=[('default', '預設值'), ('submited', '申請已提交，處理中'), ('transfered', '平台已收到賣家寄來的商品，審查中')], default='default', max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
