# Generated by Django 3.1.7 on 2021-04-25 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_sellerwithdrawrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerbankaccount',
            options={'ordering': ['seller', 'bank_name']},
        ),
        migrations.AlterModelOptions(
            name='sellerwithdrawrecord',
            options={'ordering': ['seller', 'status', 'submit_date']},
        ),
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='status',
            field=models.CharField(choices=[('default', '預設值'), ('submited', '申請已提交，處理中'), ('transfered', '已完成匯款')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 1, 52, 21, 140289), verbose_name='儲存日期'),
        ),
    ]
