# Generated by Django 2.2 on 2021-05-14 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210425_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 9, 7, 214097), verbose_name='儲存日期'),
        ),
    ]
