# Generated by Django 2.2 on 2021-05-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20210514_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 18, 3, 28, 68332), verbose_name='儲存日期'),
        ),
    ]
