# Generated by Django 2.2 on 2021-05-16 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20210514_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 16, 32, 37, 638434), verbose_name='儲存日期'),
        ),
    ]
