# Generated by Django 2.2 on 2021-05-18 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_auto_20210516_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwithdrawrecord',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 13, 9, 47, 34688), verbose_name='儲存日期'),
        ),
    ]
